name: order_delivery
description: "A Flutter delivery project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  http: ^1.2.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  get_it: ^8.0.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  flex_color_scheme: ^8.0.1
  connectivity_plus: ^6.1.0
  path: ^1.9.0
  carousel_slider: ^5.0.0
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:

  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/splash/splash.jpg
  fonts:
     - family: DancingScript
       fonts:
         - asset: fonts/dancingscript/static/DancingScript-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: PlayfairDisplay
       fonts:
         - asset: fonts/playfair/static/PlayfairDisplay-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
